# Generated by Django 4.1.5 on 2023-01-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='disagree',
            field=models.IntegerField(default=0),
        ),
    ]
